name: Scrape and Compile Air Quality Data

on:
  schedule:
    - cron: '0 */1 * * *'  # Every 1 hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas lxml

      - name: Run air quality scraper
        run: python scrape_to_csv.py

      - name: Compile CSV
        run: python compile_air_quality.py

      - name: Run air quality forecast scraper
        run: python scrape_to_csv_forecast.py

      - name: Compile forecast CSV
        run: python compile_air_quality_forecast.py

      - name: Run fire data scraper
        run: python scrape_fires.py

      - name: Move compiled CSV to docs for GitHub Pages
        run: |
          mkdir -p docs
          cp output/compiled_air_quality.csv docs/
          cp output/compiled_air_quality_forecast.csv docs/
          cp output/active_fires.csv docs/
          cp output/active_fires_on.csv docs/
          cp output/active_fires_bc.csv docs/
          cp output/active_fires_ab.csv docs/
          cp output/active_fires_sk.csv docs/
          cp output/active_fires_mb.csv docs/
          cp output/active_fires_qc.csv docs/
          cp output/active_fires_yt.csv docs/
          cp output/active_fires_nt.csv docs/

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/compiled_air_quality.csv
          git add docs/compiled_air_quality_forecast.csv
          git add docs/active_fires.csv
          git add docs/active_fires_on.csv
          git add docs/active_fires_bc.csv
          git add docs/active_fires_ab.csv
          git add docs/active_fires_sk.csv
          git add docs/active_fires_mb.csv
          git add docs/active_fires_qc.csv
          git add docs/active_fires_yt.csv
          git add docs/active_fires_nt.csv
          git commit -m "Update compiled air quality CSV, compiled air quality forecast CSV and active fires CSVs [skip ci]" || echo "No changes to commit"
          git push
